@SmartBike.Api_HostAddress = http://localhost:5219

GET {{SmartBike.Api_HostAddress}}/weatherforecast/
Accept: application/json

### Telemetry toevoegen
POST {{SmartBike.Api_HostAddress}}/api/telemetry
Content-Type: application/json

{
  "userId": 1,
  "longitude": 5.12345,
  "latitude": 52.12345,
  "timestamp": "2025-01-01T12:00:00"
}
